# ref: https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml
crds:
  install: false
dex:
  enabled: false
# redis:
#   enabled: false
# redisSecretInit:
#   enabled: false
notifications:
  enabled: false

configs:
  cm:
    users.anonymous.enabled: true
  params:
    controller.status.processors: 8 # default: 20
    controller.operation.processors: 4 # default: 10
    reposerver.parallelism.limit: 4
  rbac:
    defaultPolicy: "role:readonly"
