# ref: https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml
crds:
  install: false
dex:
  enabled: false
# redis:
#   enabled: false
# redisSecretInit:
#   enabled: false
notifications:
  enabled: false

configs:
  params:
    reposerver.parallelism.limit: 4
