gitops:
  sources:
    - repoURL: "https://helm.cilium.io"
      chart: cilium
      targetRevision: 1.15.6
      helm:
        valueFiles:
          - $gitops_source/gitops/cilium/cilium/values.yaml

  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: "privileged"
