apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argo-cd
    server: https://kubernetes.default.svc
  sources:
    - repoURL: "oci://ghcr.io/argoproj/argo-helm"
      chart: argo-cd
      targetRevision: 8.1.3
      helm:
        valueFiles:
        - $values/gitops/argo-cd/values.yaml
    - repoURL: https://github.com/mhoyer/homelab
      targetRevision: HEAD
      ref: values
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
